# ---------------------------------------------------------------------------
# Stack: network - CIS 2.4, 3.1 - 3.7
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result;
# everything below it is your inventory.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("network")
enabled_controls = <%= Cis.controls_for_stack("network").to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# --- CIS 2.4 / 3.2: virtual network flow logs ------------------------------
# CLS topic that receives the flow logs. The logging stack creates one and
# exports it as `cls_audit_topic_id`; paste it here or point at your own.
flow_log_cls_topic_id = null

#   tccli vpc DescribeVpcs --output json | jq -r '.VpcSet[].VpcId'
flow_log_targets = {
  # "prod-vpc" = {
  #   resource_id   = "vpc-xxxxxxxx"
  #   resource_type = "VPC"
  #   traffic_type  = "ALL"
  # }
}

# --- CIS 3.1 / 3.4 / 3.5 / 3.6: security group rule baseline ---------------
# Declare the COMPLETE rule set you want. Rules condemned by a selected
# control are stripped before the write; nothing is ever added.
#
#   tccli vpc DescribeSecurityGroupPolicies --SecurityGroupId sg-xxxxxxxx
#
security_groups = {
  # "app-tier" = {
  #   security_group_id = "sg-xxxxxxxx"
  #   ingress = [
  #     "ACCEPT#10.0.0.0/8#22#TCP",        # kept - private source
  #     "ACCEPT#0.0.0.0/0#443#TCP",        # kept - not a remote admin port
  #     "ACCEPT#0.0.0.0/0#22#TCP",         # dropped by 3.1 and 3.5
  #     "ACCEPT#0.0.0.0/0#3389#TCP",       # dropped by 3.1 and 3.6
  #     "ACCEPT#10.0.0.0/8#1-65535#ALL",   # dropped by 3.4
  #   ]
  #   egress = [
  #     "ACCEPT#0.0.0.0/0#ALL#ALL",
  #   ]
  # }
}

# CIS 3.4 - largest port window a single ACCEPT rule may open.
max_port_range_span = 100

# --- CIS 3.7: dedicated security group for public CLB traffic --------------
#   tccli clb DescribeLoadBalancers --output json | jq -r '.LoadBalancerSet[].LoadBalancerId'
clb_instance_ids = []

clb_ingress = [
  "ACCEPT#0.0.0.0/0#443#TCP",
  "ACCEPT#0.0.0.0/0#80#TCP",
]
