# ---------------------------------------------------------------------------
# Stack: storage - CIS 4.1, 4.3, 4.4, 4.5, 4.6, 4.7
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("storage")
enabled_controls = <%= Cis.controls_for_stack("storage").to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# Only needed for cross-account buckets. By default the APPID is read from the
# bucket name suffix.
app_id = <%= (v = ENV['TENCENTCLOUD_APPID']).to_s.empty? ? 'null' : v.to_json %>

# --- the buckets to harden -------------------------------------------------
# Key = full bucket name including the APPID suffix.
#
# managed = false (default)
#   Policy-only. Covers 4.1 (deny anonymous), 4.4 (require TLS) and 4.5 (no
#   public network access). 4.3 / 4.6 / 4.7 are reported as unreachable, and
#   `cis plan` will say so rather than pretend.
#
# managed = true
#   This stack owns tencentcloud_cos_bucket, so ACL, access logging and
#   server-side encryption are all enforced. Import an existing bucket first:
#
#     terraspace import storage 'module.bucket["my-data-1250000000"].tencentcloud_cos_bucket.this[0]' my-data-1250000000
#
buckets = {}

# buckets = {
#   # policy-only: closes public access on a bucket you do not want in state
#   "legacy-assets-1250000000" = {}
#
#   # fully managed: everything in section 4 that Terraform can reach
#   "app-data-1250000000" = {
#     managed           = true
#     log_target_bucket = "cos-access-logs-1250000000" # 4.3
#     log_prefix        = "app-data/"                  # 4.3
#     kms_id            = "kms-abcd1234"               # 4.7, omit for 4.6 only
#     versioning_enable = true
#
#     # ALLOW rules your workload needs. COS evaluates DENY first, so these
#     # cannot re-open what CIS closed.
#     extra_policy_statements = []
#   }
# }

# Tags applied to buckets this stack manages (managed = true only).
tags = {
  "managed-by" = "cis"
  "cis"        = "section-4"
}
