# ---------------------------------------------------------------------------
# Stack: logging - CIS 2.1, 2.2, 2.3, 2.5, 2.9 - 2.20
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("logging")
enabled_controls = <%= Cis.controls_for_stack("logging").to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# APPID - needed by CIS 2.2 to build the COS bucket policy ARN.
#   tccli cam GetUserAppId
app_id = <%= (v = ENV['TENCENTCLOUD_APPID']).to_s.empty? ? 'null' : v.to_json %>

# --- CIS 2.3 / 2.20: Cloud Log Service -------------------------------------
# Leave both null to have this stack create a logset + topic. Point cls_topic_id
# at an existing topic to reuse it - but note that reusing makes CIS 2.20
# unreachable, because retention is a property of the topic resource.
cls_logset_id = null
cls_topic_id  = null

cls_logset_name = "cis-benchmark-audit"
cls_topic_name  = "cis-benchmark-cloudaudit"

# CIS 2.20 requires >= 365. Use -1 for permanent retention.
cls_retention_days = 365

# --- CIS 2.1: CloudAudit track ---------------------------------------------
# Destination for the operational log records. storage_name is the bucket name
# for "cos" or the topic id for "cls".
audit_track_storage = null
# audit_track_storage = {
#   storage_type   = "cos"
#   storage_name   = "cis-cloudaudit-1250000000"
#   storage_prefix = "cis"
#   storage_region = "ap-guangzhou"
# }

# --- CIS 2.2: the COS bucket behind CloudAudit -----------------------------
# A deny-anonymous bucket policy is attached. The bucket is not imported.
cloudaudit_cos_bucket = null
# cloudaudit_cos_bucket = "cis-cloudaudit-1250000000"

# --- CIS 2.5: EdgeOne real time log delivery -------------------------------
edgeone_log_delivery = null
# edgeone_log_delivery = {
#   zone_id     = "zone-xxxxxxxx"
#   task_name   = "cis-edgeone-access-log"
#   entity_list = ["www.example.com"]
#   log_type    = "domain"
#   task_type   = "cls"
#   area        = "global"
# }

# --- CIS 2.9 - 2.19: log monitoring and alerts -----------------------------
# Where the alerts go. Set one of the two.
alarm_notice_ids = []

alarm_notice_receivers = []
# alarm_notice_receivers = [
#   {
#     receiver_type     = "Uin"
#     receiver_ids      = [100000000001]
#     receiver_channels = ["Email", "Sms"]
#   },
# ]

# The built-in queries assume CloudAudit's standard CLS field mapping. Verify
# them against your own topic once, then override the ones that need it.
alarm_overrides = {}
# alarm_overrides = {
#   "2.16" = { name = "root-usage", query = "principalId:\"root\"" }
# }
