# ---------------------------------------------------------------------------
# Stack: kubernetes - CIS 6.2, 6.7, 6.9
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("kubernetes")
enabled_controls = <%= Cis.controls_for_stack("kubernetes").to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# --- the clusters to harden ------------------------------------------------
#   tccli tke DescribeClusters
clusters = {}

# clusters = {
#   "cls-abcd1234" = {
#     cluster_intranet           = true
#     cluster_intranet_subnet_id = "subnet-abcd1234" # required by 6.9
#   }
# }

# --- CIS 6.2: cloud monitoring ---------------------------------------------
#   tccli monitor DescribePrometheusInstances
prometheus_instance_id  = null
monitor_enable_external = false

# --- CIS 6.7: network policy add-on ----------------------------------------
# Confirm the add-on name for your cluster version before applying:
#   tccli tke DescribeAddonValues --ClusterId cls-abcd1234 --AddonName NetworkPolicy
network_policy_addon_name = "NetworkPolicy"
network_policy_version    = null

# --- CIS 6.9: public API server --------------------------------------------
# true  -> this stack owns tencentcloud_kubernetes_cluster_endpoint and closes
#          the public endpoint. Import existing endpoints first:
#
#   terraspace import kubernetes 'tencentcloud_kubernetes_cluster_endpoint.this["cls-abcd1234"]' cls-abcd1234
#
# false -> 6.9 is reported as unreachable instead.
manage_cluster_endpoint = true

tags = {
  "managed-by" = "cis-terraspace"
  "cis"        = "section-6"
}
