# ---------------------------------------------------------------------------
# Stack: audit - read-only assessment
#
# This stack declares no managed resources: only data sources, locals, check
# blocks and outputs. `cis scan` runs it and reads `cis_findings` back.
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result
# narrowed to the controls the provider can actually observe; everything below
# it is tuning for the probes.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_audit
# Without this the stack would default to [], every data source would be
# skipped, and the scan would report a clean bill of health it never checked.
enabled_controls = <%= Cis.controls_for_audit.to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# --- CIS 1.15: which policy names are understood to grant *:* --------------
# The provider does not expose policy documents, so this probe is name based.
# Add any in-house policy you know to be full admin, or the check will miss it.
admin_policy_names = [
  "AdministratorAccess",
  "QcloudResourceFullAccess",
]

# --- CIS 2.20: minimum Logstore retention ----------------------------------
# A topic with period <= 0 stores permanently and always passes.
cls_min_retention_days = 365

# --- CIS 3.4: what counts as a coarse rule ---------------------------------
# An internet-facing ACCEPT rule spanning more ports than this is not
# "fine grained". Keep it in sync with the network stack's own value.
max_port_range_span = 100

# --- CIS 3.3: next-hop types that leave the VPC ----------------------------
peering_next_types = [
  "PEERCONNECTION",
  "CCN",
  "DIRECTCONNECT",
  "VPN",
]

# --- CIS 4.1 / 4.2: ACLs treated as public ---------------------------------
public_acls = [
  "public-read",
  "public-read-write",
]

# --- shared: CIDRs treated as "the internet" -------------------------------
world_cidrs = [
  "0.0.0.0/0",
  "::/0",
]
