# ---------------------------------------------------------------------------
# Stack: database - CIS 5.1 - 5.6, TencentDB for MySQL
#
# ERB-rendered by Terraspace. The generated block is the CLI filter result.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("database")
enabled_controls = <%= Cis.controls_for_stack("database").to_json %>
# <<< generated

region = "<%= ENV.fetch('TENCENTCLOUD_REGION', 'ap-guangzhou') %>"

# --- the instances to harden -----------------------------------------------
#   tccli cdb DescribeDBInstances --filter InstanceIds
mysql_instances = {}

# mysql_instances = {
#   "cdb-abcd1234" = {}
#   "cdb-efgh5678" = {
#     security_group_ids   = ["sg-private-db"]
#     audit_log_expire_day = 1095
#     kms_key_id           = "kms-11112222"
#   }
# }

# --- CIS 5.2: private access only ------------------------------------------
# Attach groups you already manage...
default_security_group_ids = []

# ...or let this stack create one. allowed_cidrs still goes through the
# section 3 baseline, so 0.0.0.0/0 gets dropped instead of applied.
db_security_group = {
  create = false
}
# db_security_group = {
#   create        = true
#   name          = "cis-mysql-private"
#   allowed_cidrs = ["10.0.0.0/8", "172.16.0.0/12"]
#   port          = 3306
# }

# The public endpoint itself is not managed here - see the variable docs.
# Flip to true after confirming WanStatus is closed on every instance.
wan_endpoint_reviewed = false

# --- CIS 5.3 / 5.4: audit service ------------------------------------------
audit_all            = true
audit_log_expire_day = 365 # benchmark wants > 6 months

# --- CIS 5.5 / 5.6: transparent data encryption ----------------------------
# WARNING: enabling TDE is irreversible. Leave the controls out of the run
# until you have verified the instances can take it.
#
# kms_key_id = null  -> TDE with the Tencent managed key: satisfies 5.5 only.
# kms_key_id = "kms-xxxx" -> customer managed protector: satisfies 5.5 and 5.6.
kms_key_id     = null
kms_key_region = null

tags = {
  "managed-by" = "cis"
  "cis"        = "section-5"
}
