# ---------------------------------------------------------------------------
# Stack: iam - CIS section 1
#
# This file is ERB-rendered by Terraspace. The generated block below is the
# bridge between `bin/cis --only/--exclude/--section/--tag/--profile` and the
# Terraform code: whatever the filter selected shows up in enabled_controls,
# and every resource in main.tf is gated on it.
#
# Do not edit the generated block. Do edit the target lists underneath it.
# ---------------------------------------------------------------------------

# >>> generated by Cis.controls_for_stack("iam")
enabled_controls = <%= Cis.controls_for_stack("iam").to_json %>
# <<< generated

# --- CIS 1.4: CAM sub-users holding a console password ---------------------
# Every UIN listed here will be forced to present a soft token (stoken) at
# console login and at sensitive operations.
#
#   tccli cam ListUsers --filter-console 1 --output json | jq '.Data[].Uin'
#
cam_console_user_uins = []

# Accepted MFA factors. 1 = required, 0 = not required.
mfa_login_flag = {
  phone  = 0
  stoken = 1
  wechat = 0
}

mfa_action_flag = {
  phone  = 0
  stoken = 1
  wechat = 0
}
